---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: oraclelinux
    image: oraclelinux:9
    pre_build_image: true
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy